# Generated by Django 4.1.3 on 2022-12-22 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 22, 11, 29, 28, 110686, tzinfo=datetime.timezone.utc)),
        ),
    ]
