# Generated by Django 4.1.3 on 2022-11-22 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 22, 1, 41, 12, 429421, tzinfo=datetime.timezone.utc)),
        ),
    ]
