# Generated by Django 4.1.3 on 2022-11-22 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 22, 1, 46, 15, 81768, tzinfo=datetime.timezone.utc)),
        ),
    ]
