# Generated by Django 4.1.3 on 2022-12-09 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 9, 13, 18, 25, 515435, tzinfo=datetime.timezone.utc)),
        ),
    ]
