# Generated by Django 4.1.3 on 2022-12-12 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 12, 12, 18, 49, 22, 403630, tzinfo=datetime.timezone.utc)),
        ),
    ]
